### ISSUE TITLE
Retropie 4.4

### ISSUE THREAD

**Issue by ukbonkerz** [Camble/Safe-Power-Monitor#11]
Script no longer works in Retropie 4.4 and Raspberry Pi 3b+. When initially starting the script the pi instantly shuts down.  After rebooting the script is not working and errors when trying to start. 

pi@retropie:~ $ python ~/Safe-Power-Monitor/safe_power_monitor.py
Traceback (most recent call last):
  File "/home/pi/Safe-Power-Monitor/safe_power_monitor.py", line 264, in <module                              >
    main()
  File "/home/pi/Safe-Power-Monitor/safe_power_monitor.py", line 237, in main
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: 'module' object has no attribute 'GPIO'

the script works ok with retropie retropie-4.3.15-rpi2_rpi3 with the 3b+

Thanks

edit:  Tried going back to retropie-4.3.15-rpi2_rpi3 and i get the same error, i think the problem is with the latest commit.

**Comment by Camble** [comment]
Please pull the latest version of the script. This issue has been resolved.
